Skip external mounts with disabled previews
nextcloud/previewgenerator pull request #190
Opened 2020-05-04 16:04 UTC by hashworks

For external storage mounts one can disable previews:
![setting](https://fb.hash.works/R2qz3/)

This change respects this setting and skips folders with disabled previews:
```
2020-05-04T15:52:15+00:00 Scanning folder /hashworks/files
2020-05-04T15:52:15+00:00 Skipping folder /hashworks/files/NoMedia
2020-05-04T15:52:15+00:00 Scanning folder /hashworks/files/Photos
[...]
2020-05-04T15:52:15+00:00 Skipping folder /hashworks/files/GDrive
```

Resolves #151.

2020-05-04 16:08 UTC, hashworks commented
Please note that the CI fails because it's using an old PHP version: `This version of Nextcloud requires at least PHP 7.2<br/>You are currently running 7.0.33. Please update your PHP version.`

2020-05-04 16:15 UTC, hashworks commented
Additionally, the 7.2 test fails because of a PHPUnit error:
```
$ sh -c "phpunit --configuration phpunit.xml"
PHP Fatal error:  Declaration of OCA\PreviewGenerator\Tests\WatcherTest::setUp() must be compatible with Test\TestCase::setUp(): void in /home/travis/build/rullzer/server/apps/previewgenerator/tests/WatcherTest.php on line 37
PHP Stack trace:
PHP   1. {main}() /home/travis/build/rullzer/vendor/phpunit/phpunit/phpunit:0
PHP   2. PHPUnit\TextUI\Command::main() /home/travis/build/rullzer/vendor/phpunit/phpunit/phpunit:61
PHP   3. PHPUnit\TextUI\Command->run() /home/travis/build/rullzer/vendor/phpunit/phpunit/src/TextUI/Command.php:163
PHP   4. PHPUnit\TextUI\Command->handleArguments() /home/travis/build/rullzer/vendor/phpunit/phpunit/src/TextUI/Command.php:171
PHP   5. PHPUnit\Util\Configuration->getTestSuiteConfiguration() /home/travis/build/rullzer/vendor/phpunit/phpunit/src/TextUI/Command.php:929
PHP   6. PHPUnit\Util\Configuration->getTestSuite() /home/travis/build/rullzer/vendor/phpunit/phpunit/src/Util/Configuration.php:874
PHP   7. PHPUnit\Framework\TestSuite->addTestFiles() /home/travis/build/rullzer/vendor/phpunit/phpunit/src/Util/Configuration.php:1005
PHP   8. PHPUnit\Framework\TestSuite->addTestFile() /home/travis/build/rullzer/vendor/phpunit/phpunit/src/Framework/TestSuite.php:452
PHP   9. PHPUnit\Util\FileLoader::checkAndLoad() /home/travis/build/rullzer/vendor/phpunit/phpunit/src/Framework/TestSuite.php:354
PHP  10. PHPUnit\Util\FileLoader::load() /home/travis/build/rullzer/vendor/phpunit/phpunit/src/Util/FileLoader.php:47
PHP  11. include_once() /home/travis/build/rullzer/vendor/phpunit/phpunit/src/Util/FileLoader.php:59
```

2020-05-04 16:19 UTC, hashworks commented
There we go :) All fixed.

2020-06-04 14:23 UTC, hashworks commented
@rullzer Anything you want me to adjust here?

2020-10-23 12:39 UTC, MichaIng commented
Great, also updating the tests PHP versions is what I just thought as well 😉.

2020-12-21 09:05 UTC, rullzer submitted a review, later dismissed
Could you rebase on master?

2020-12-21 15:27 UTC, hashworks commented
Rebase done.

2021-03-05 22:46 UTC, poisonborz commented
Please someone merge this 🙏

2021-04-21 10:44 UTC, cClaude commented
@hashworks it seem that a rebase is still required.

@rullzer is there any change to have this merged ?

2021-04-21 10:46 UTC, MichaIng commented
> it seem that a rebase is still required.

Base branch is correct, only conflicts need to be resolved.

2021-04-21 10:53 UTC, hashworks commented
Rebase done.

2021-09-19 13:37 UTC, szaimen commented
Merge?

2021-11-10 12:22 UTC, st3iny requested changes
This will break if `files_external` is disabled. Please make the `GlobalStoragesService` parameter of the constructor optional and implement checks when using it later.

2021-12-01 22:51 UTC, st3iny commented
@hashworks I can take over if you are lacking the time/interest in this fix. I really think it is a great addition to the app.

2021-12-01 23:02 UTC, hashworks commented
I'll fix this on the weekend.

2021-12-05 16:29 UTC, hashworks commented
Rebased and `GlobalStoragesService` made optional. Tested it, works with and without the "External storage support" app.

2021-12-06 14:08 UTC, st3iny approved these changes

2021-12-06 14:08 UTC, merged